services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app                # kodu host'tan mount et (dev için)
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: .
    command: rq worker default
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data: